import { useRouter } from "next/router";
import React from "react";
import Head from "next/head";
import { PostDetailProvider } from "../../../contexts/Post/detail";
import PostEditContainer from "../../../components/Post/containers/PostEditContainer";

function Edit(props) {
  const router = useRouter();
  const { params } = router.query;
  console.log(params);

  return (
    <div className="mb-40 max-w-5xl mx-auto">
      <Head>
        <title>모의 투자 사이트 | 커뮤니티</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-11 px-9 ">
        <div className="text-lg mb-9 pb-2 border-b-2 text-gray-600 font-bold">
          게시글 수정
        </div>
        <PostDetailProvider id={params}>
            <PostEditContainer />
        </PostDetailProvider>
      </div>
    </div>
  );
}

export default Edit;
