import React from "react";
import CreatePost from "../components/Post/CreatePost";
import Head from "next/head";

function createPost(props) {
  return (
    <div className="mb-40 max-w-5xl mx-auto">
      <Head>
        <title>모의 투자 사이트 | 커뮤니티 글쓰기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-21">
        <div className="font-bold text-2xl my-11 border-b-2 pb-6 border-slate-900">
          커뮤니티 글쓰기
        </div>
      </div>
      <CreatePost />
    </div>
  );
}

export default createPost;
