import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>모의 투자 사이트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center my-12'>
        <p className='text-5xl mb-16'>모의투자 사이트</p>
        <Link href="/exchange/KRW-BTC"><button>시작하기</button></Link>
      </div>
      </div>
  )
}
