import Head from 'next/head'
import Link from 'next/link'
import AppLayout from '../components/AppLayout'
import AuthService from '../services/auth.service';
import { useState, useEffect } from 'react';

export default function Home() {
  const [currentUser, setCurrentUser] = useState(undefined);

  useEffect(() => {
    const user = AuthService.getCurrentUser();

    if(user){
      setCurrentUser(user);
    }
  }, []);

  const logout = () => {
    AuthService.logout();
  };

  return (
    <div>
      <Head>
        <title>모의 투자 사이트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center my-12'>
        <p className='text-5xl mb-16'>모의투자 사이트</p>
        <Link href="/exchange/KRW-BTC"><button>시작하기</button></Link>
      </div>
      </div>
  )
}
