import React from "react";
import LoginForm from "../components/User/LoginForm";
import Head from "next/head";
function login(props) {
  return (
    <div>
      <Head>
        <title>모의 투자 사이트 | 로그인</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-24 text-center">
        <div className="font-bold text-3xl my-11">로그인</div>
        <LoginForm />
      </div>
      </div>
  );
}

export default login;
