import React, {useState} from "react";
import LoginForm from '../components/User/LoginForm'
import Head from "next/head";

function login(props) {

  return (
    <div>
      <Head>
        <title>모의 투자 사이트 | 로그인</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center my-11 font-bold text-2xl">
        Cryptocurrency Simulator 
      </div>
      <LoginForm />
    </div>
  );
}

export default login;
