import React from 'react';
import Head from "next/head";
import UserProfile from '../components/User/UserProfile';

function profile(props) {
    return (
        <div>
      <Head>
        <title>모의 투자 사이트 | 프로필</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center my-11 font-bold text-2xl">
        Cryptocurrency Simulator 
      </div>
      <UserProfile />
    </div>
    );
}

export default profile;