import React from "react";
import Head from "next/head";
import UserProfile from "../components/User/UserProfile";

function profile(props) {
  return (
    <div>
      <Head>
        <title>모의 투자 사이트 | 프로필</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-24 text-center">
        <div className="font-bold text-3xl my-11">기본 정보</div>
        <UserProfile />
      </div>
    </div>
  );
}

export default profile;
