import React from "react";
import SignUpForm from "../components/User/SignUpForm";
import Head from "next/head";

function signup(props) {
  return (
    <div>
      <Head>
        <title>모의 투자 사이트 | 회원가입</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-24 text-center">
        <div className="font-bold text-3xl my-11">회원가입</div>
        <SignUpForm />
      </div>
    </div>
  );
}

export default signup;
