import React from "react";
import TestForm from "../components/Test/TestForm";
import Head from "next/head";

function Test(props) {
  return (
    <div className="mb-40 max-w-5xl mx-auto">
        <Head>
          <title>모의 투자 사이트 | 커뮤니티</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="py-11 px-9 ">
          <div className="text-lg mb-9 pb-2 border-b-2 text-gray-600 font-bold">
            비트코인 투자 테스트
          </div>
        <TestForm />
        </div>
    </div>
  );
}

export default Test;
