import React from "react";
import TestForm from "../components/Test/TestForm";
import Head from "next/head";

function Test(props) {
  return (
    <div>
      <Head>
        <title>모의 투자 사이트 | 테스트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-24 text-center">
        <div className="font-bold text-3xl my-11">비트코인 투자 테스트</div>
        <TestForm />
      </div>
    </div>
  );
}

export default Test;
