import React from "react";
import Test from "../components/Test/Test";
import Head from "next/head";
import List from "../components/Test/List";

function TestPage(props) {
  return (
    <div >
      <Head>
        <title>모의 투자 사이트 | 테스트</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center my-11 font-bold text-2xl">
        비트코인 투자 테스트
      </div>

      {/* <div className="grid grid-cols-5 gap-2"> */}
        {/* <div className="col-span-3">
        <List />
        </div> */}
      {/* <div className="col-span-2 mr-24"> */}
      <Test />
      {/* </div> */}
     
      {/* </div> */}
      
    </div>
  );
}

export default TestPage;
