import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Post from "../../components/Post/index";
import PostButton from "../../components/Post/PostButton";
import DetailPost from "../../components/Post/DetailPost";

function community(props) {
  const router = useRouter();
  const { params } = router.query;
  console.log(params);

  if (params === undefined) {
    return (
      <div className="mb-40 max-w-5xl mx-auto">
        <Head>
          <title>모의 투자 사이트 | 커뮤니티</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="my-21">
          <div className="font-bold text-2xl my-11 border-b-2 pb-6 border-slate-900">커뮤니티</div>
        </div>
        <PostButton />
       <Post />
       
      </div>
    );
  } else {
    return (
      <div>
        <Head>
          <title>모의 투자 사이트 | 커뮤니티</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mb-40 max-w-5xl mx-auto">
          <div className="font-bold text-3xl my-11 border-b-2 pb-6 border-slate-900">커뮤니티</div>
          <div className="max-w-6xl mx-auto">
            <DetailPost params={params} />
          </div>
        </div>
      </div>
    );
  }
}
export default community;
