import React from 'react';
import { useRouter } from "next/router";
import Head from "next/head";
import Post from '../../components/Post/index';
import PostButton from '../../components/Post/PostButton';
import DetailPost from '../../components/Post/DetailPost';

function community(props) {

    const router = useRouter() 
    const { params } = router.query
    console.log(params)
    
    if(params === undefined){
        return(
            <div>
            <Head>
                <title>모의 투자 사이트 | 커뮤니티</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-center mt-11 font-bold text-2xl">
                Cryptocurrency Simulator 
            </div>
            <div className="text-center my-6 font-bold text-2xl">
                커뮤니티
            </div>
            <PostButton />
            <Post />
        </div>
        )
    } 
    else {
        return (
            <div>
            <Head>
                <title>모의 투자 사이트 | 커뮤니티</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-center mt-11 font-bold text-2xl">
                Cryptocurrency Simulator 
            </div>
            <div className="text-center my-6 font-bold text-2xl">
                커뮤니티
            </div>
            <div className="max-w-6xl mx-auto py-4">
                <DetailPost params={params} />

            </div>
            </div>
        )
    }
}
export default community;