import React from "react";
import Head from "next/head";
import PostForm from "../../components/Post/components/PostForm";

function Post(props) {
  return (
    <div className="mb-40 max-w-5xl mx-auto">
      <Head>
        <title>모의 투자 사이트 | 커뮤니티 글쓰기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-11 px-9 ">
        <div className="text-lg mb-9 pb-2 border-b-2 text-gray-600 font-bold">
          글쓰기
        </div>
        <PostForm />
      </div>
    </div>
  );
}

export default Post;
