import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import axios from "axios";
import useInput from "../../components/hooks/useInput";
import authHeader from "../../services/auth-header";
import Link from "next/link";

function editPost(props) {
  const router = useRouter();
  const [content, onChangeContent] = useInput("");
  const [title, onChangeTitle] = useInput("");
  const { params } = router.query;
  console.log(params);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await axios.post(
        `http://localhost:9090/v1/api/posts/${params}`,
        {
          content,
          title,
        },
        {
          headers: authHeader(),
        },
        (error) => {
          console.log(error);
        }
      );
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <div className="mb-40 max-w-5xl mx-auto">
      <Head>
        <title>모의 투자 사이트 | 커뮤니티</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-21">
        <div className="font-bold text-2xl my-11 border-b-2 pb-6 border-slate-900">
          커뮤니티
        </div>
      </div>
      <div className="border-slate-800">
        <div className="font-bold text-lg border-b-2 pb-4 border-slate-200">
          게시글 수정
        </div>
        <form className="border-slate-800" onClick={handleSubmit}>
          <div className="flex border-b-2 py-6">
            <label className="mr-8 text-lg my-auto">제목</label>
            <input
              className="border-2 rounded-md w-96 h-11 text-lg"
              value={title}
              onChange={onChangeTitle}
              type="text"
              required
            />
          </div>
          <div className="w-full py-11">
            <input
              className="px-11 w-full h-72 border text-lg"
              type="text"
              placeholder="커뮤니티 글쓰기"
              value={content}
              onChange={onChangeContent}
              required
            />
          </div>
          <div className="flex justify-end">
            {/* router이용하여 뒤로가기  */}
            <button
              onClick={() => router.back()}
              className="bg-red-100 rounded-xl py-2 mr-2 w-36 font-bold  h-14"
              type="submit"
            >
              취소
            </button>
            <Link href="/community">
              <button
                className="bg-blue-100 rounded-xl py-2 mr-2 w-36 font-bold h-14"
                type="submit"
              >
                확인
              </button>
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
}

export default editPost;
