import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import axios from "axios";
import useInput from "../../components/hooks/useInput";
import authHeader from "../../services/auth-header";
import Link from "next/link";

function editPost(props) {
  const router = useRouter();
  const [content, onChangeContent] = useInput("");
  const [title, onChangeTitle] = useInput("");
  const { params } = router.query;
  console.log(params);

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await axios.post(
        `http://localhost:9090/v1/api/posts/${params}`,
        {
          content,
          title,
        },
        {
          headers: authHeader(),
        },
        (error) => {
          console.log(error);
        }
      );
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <div>
      <Head>
        <title>모의 투자 사이트 | 커뮤니티</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center mt-11 font-bold text-2xl">
        Cryptocurrency Simulator
      </div>
      <div className="text-center my-6 font-bold text-2xl">게시글 수정</div>
      <div className="border-slate-800 text-center">
        <form
          className="inline-block border-t-2 border-slate-800"
          onClick={handleSubmit}
        >
          <div className="flex border-b-2 py-6">
            <label className="mr-8">제목</label>
            <input
              className="border-2 rounded-md w-96"
              value={title}
              onChange={onChangeTitle}
              type="text"
              required
            />
          </div>
          <div className="w-full py-11">
            <input
              className="px-11 w-full h-72 border"
              type="text"
              placeholder="커뮤니티 글쓰기"
              value={content}
              onChange={onChangeContent}
              required
            />
          </div>
          <div className="flex justify-end">
            {/* router이용하여 뒤로가기  */}
            <button
              onClick={() => router.back()}
              className="bg-slate-100 rounded-xl px-2 py-2 mr-2 w-24"
              type="submit"
            >
              취소
            </button>
            <Link href="/community">
              <button
                className="bg-slate-400 rounded-xl px-2 py-2 mr-2 w-24"
                type="submit"
              >
                확인
              </button>
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
}

export default editPost;
