import React from "react";
import SignUpForm from "../../components/User/SignUpForm";
import Head from "next/head";

function signup(props) {
  return (
    <div className="mb-40 max-w-5xl mx-auto">
    <Head>
      <title>모의 투자 사이트 | 로그인</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="py-11 px-9 text-center">
      <div className="text-4xl my-11 pb-9 px-36 font-bold ml-2 border-b-2 inline-block">
        회원가입
      </div>
        <SignUpForm />
      </div>
    </div>
  );
}

export default signup;
